import { useState, useMemo, useEffect } from 'react'
import { BookOpen, Mail, Clock, Plane, Navigation, Gauge, Timer, PlaneLanding, Fuel } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

interface LogBookPanelProps {
  initialFuelGallons: number
  fuelConsumptionGPH: number
  flightDate: string
  pilotName: string
  aircraftReg: string
  routeFrom?: string
  routeTo?: string
}

export function LogBookPanel({
  initialFuelGallons,
  fuelConsumptionGPH,
  flightDate,
  pilotName,
  aircraftReg,
  routeFrom = '',
  routeTo = '',
}: LogBookPanelProps) {
  // Flight type
  const [flightType, setFlightType] = useState<'private' | 'instruction'>('private')
  const [instructorName, setInstructorName] = useState('')

  // Airports - initialized from Trip Planning
  const [departure, setDeparture] = useState(routeFrom)
  const [destination, setDestination] = useState(routeTo)

  // Sync with Trip Planning selections
  useEffect(() => {
    if (routeFrom) setDeparture(routeFrom)
  }, [routeFrom])

  useEffect(() => {
    if (routeTo) setDestination(routeTo)
  }, [routeTo])

  // Hobbs meter (hourmeter)
  const [hobbsStart, setHobbsStart] = useState<number | ''>('')
  const [hobbsEnd, setHobbsEnd] = useState<number | ''>('')

  // Block times (engine start/stop)
  const [blockOut, setBlockOut] = useState('')
  const [blockIn, setBlockIn] = useState('')

  // Flight time (manual override)
  const [flightTime, setFlightTime] = useState('')

  // Landings
  const [landings, setLandings] = useState<number | ''>(1)

  // Fuel
  const [fuelRemaining, setFuelRemaining] = useState<number | ''>('')

  // Calculate block time from times
  const calculatedBlockTime = useMemo(() => {
    if (!blockOut || !blockIn) return null

    const [outHours, outMinutes] = blockOut.split(':').map(Number)
    const [inHours, inMinutes] = blockIn.split(':').map(Number)

    if (isNaN(outHours) || isNaN(outMinutes) || isNaN(inHours) || isNaN(inMinutes)) {
      return null
    }

    let outTotal = outHours * 60 + outMinutes
    let inTotal = inHours * 60 + inMinutes

    // Handle midnight crossover
    if (inTotal < outTotal) {
      inTotal += 24 * 60
    }

    return inTotal - outTotal
  }, [blockOut, blockIn])

  // Calculate Hobbs time
  const hobbsTime = useMemo(() => {
    if (hobbsStart === '' || hobbsEnd === '') return null
    const diff = Number(hobbsEnd) - Number(hobbsStart)
    return diff > 0 ? diff : null
  }, [hobbsStart, hobbsEnd])

  // Fuel consumption
  const fuelUsed = useMemo(() => {
    if (fuelRemaining === '') return null
    return initialFuelGallons - Number(fuelRemaining)
  }, [initialFuelGallons, fuelRemaining])

  // Get current time
  const getCurrentTime = () => {
    const now = new Date()
    return `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`
  }

  // Format time in hours and minutes
  const formatTime = (minutes: number) => {
    const h = Math.floor(minutes / 60)
    const m = minutes % 60
    return `${h}h${String(m).padStart(2, '0')}`
  }

  // Send email
  const sendLogbookEmail = () => {
    const blockTimeStr = calculatedBlockTime ? formatTime(calculatedBlockTime) : flightTime || 'N/A'
    const hobbsTimeStr = hobbsTime ? hobbsTime.toFixed(1) : 'N/A'

    const subject = `Flight Log ${aircraftReg} - ${flightDate}`
    const body = `
FLIGHT LOG - ${aircraftReg}
================================

Date: ${flightDate}
Pilot: ${pilotName || 'N/A'}
Flight Type: ${flightType === 'private' ? 'Private' : 'Instruction'}
${flightType === 'instruction' ? `Instructor: ${instructorName || 'N/A'}` : ''}

ROUTE
-----
Departure: ${departure || 'N/A'}
Destination: ${destination || 'N/A'}

TIMES
-----
Block Out: ${blockOut || 'N/A'}
Block In: ${blockIn || 'N/A'}
Block Time: ${blockTimeStr}

Hobbs Start: ${hobbsStart || 'N/A'}
Hobbs End: ${hobbsEnd || 'N/A'}
Hobbs Time: ${hobbsTimeStr}

Flight Time: ${flightTime || blockTimeStr}

LANDINGS
--------
${landings || 0}

FUEL
----
Initial: ${initialFuelGallons} gal
Remaining: ${fuelRemaining || 'N/A'} gal
Used: ${fuelUsed !== null ? fuelUsed.toFixed(1) : 'N/A'} gal

================================
Generated by C206 Flight Analyzer
    `.trim()

    const mailtoLink = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
    window.location.href = mailtoLink
  }

  return (
    <div className="aviation-card p-5">
      <div className="section-header flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <BookOpen className="h-5 w-5 text-primary" />
          <h3 className="text-lg font-semibold">Flight Log</h3>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={sendLogbookEmail}
          className="h-8 px-3"
        >
          <Mail className="h-4 w-4 mr-1" />
          Send
        </Button>
      </div>

      {/* Mobile email button - visible at TOP when section-header is hidden */}
      <div className="lg:hidden mb-4">
        <Button
          variant="default"
          onClick={sendLogbookEmail}
          className="w-full"
        >
          <Mail className="h-4 w-4 mr-2" />
          Send Flight Log
        </Button>
      </div>

      <div className="space-y-4">
        {/* Flight Type */}
        <div>
          <Label className="text-sm text-muted-foreground mb-2 flex items-center gap-1.5">
            <Plane className="h-3.5 w-3.5" />
            Flight Type
          </Label>
          <div className="grid grid-cols-2 gap-2">
            <Button
              variant={flightType === 'private' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setFlightType('private')}
              className="w-full"
            >
              Private
            </Button>
            <Button
              variant={flightType === 'instruction' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setFlightType('instruction')}
              className="w-full"
            >
              Instruction
            </Button>
          </div>
          {flightType === 'instruction' && (
            <Input
              type="text"
              placeholder="Instructor name"
              value={instructorName}
              onChange={(e) => setInstructorName(e.target.value)}
              className="mt-2"
            />
          )}
        </div>

        <div className="section-divider" />

        {/* Airports */}
        <div>
          <Label className="text-sm text-muted-foreground mb-2 flex items-center gap-1.5">
            <Navigation className="h-3.5 w-3.5" />
            Route
          </Label>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <Input
                type="text"
                placeholder="From (ICAO)"
                value={departure}
                onChange={(e) => setDeparture(e.target.value.toUpperCase())}
                className="font-mono text-center"
                maxLength={4}
              />
            </div>
            <div>
              <Input
                type="text"
                placeholder="To (ICAO)"
                value={destination}
                onChange={(e) => setDestination(e.target.value.toUpperCase())}
                className="font-mono text-center"
                maxLength={4}
              />
            </div>
          </div>
        </div>

        <div className="section-divider" />

        {/* Hobbs Meter */}
        <div>
          <Label className="text-sm text-muted-foreground mb-2 flex items-center gap-1.5">
            <Gauge className="h-3.5 w-3.5" />
            Hobbs
          </Label>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <Label className="text-xs text-muted-foreground">Start</Label>
              <Input
                type="number"
                step="0.1"
                placeholder="0.0"
                value={hobbsStart}
                onChange={(e) => setHobbsStart(e.target.value ? parseFloat(e.target.value) : '')}
                className="font-mono text-right"
              />
            </div>
            <div>
              <Label className="text-xs text-muted-foreground">End</Label>
              <Input
                type="number"
                step="0.1"
                placeholder="0.0"
                value={hobbsEnd}
                onChange={(e) => setHobbsEnd(e.target.value ? parseFloat(e.target.value) : '')}
                className="font-mono text-right"
              />
            </div>
          </div>
          {hobbsTime !== null && (
            <div className="mt-2 text-center">
              <span className="text-sm text-muted-foreground">Hobbs Time: </span>
              <span className="font-mono font-semibold text-primary">{hobbsTime.toFixed(1)}</span>
            </div>
          )}
        </div>

        <div className="section-divider" />

        {/* Block Times */}
        <div>
          <Label className="text-sm text-muted-foreground mb-2 flex items-center gap-1.5">
            <Clock className="h-3.5 w-3.5" />
            Block Time
          </Label>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <Label className="text-xs text-muted-foreground">Block Out</Label>
              <div className="flex gap-1">
                <Input
                  type="time"
                  value={blockOut}
                  onChange={(e) => setBlockOut(e.target.value)}
                  className="font-mono flex-1"
                />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setBlockOut(getCurrentTime())}
                  className="px-2"
                  title="Current time"
                >
                  <Clock className="h-4 w-4" />
                </Button>
              </div>
            </div>
            <div>
              <Label className="text-xs text-muted-foreground">Block In</Label>
              <div className="flex gap-1">
                <Input
                  type="time"
                  value={blockIn}
                  onChange={(e) => setBlockIn(e.target.value)}
                  className="font-mono flex-1"
                />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setBlockIn(getCurrentTime())}
                  className="px-2"
                  title="Current time"
                >
                  <Clock className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
          {calculatedBlockTime !== null && (
            <div className="mt-2 text-center">
              <span className="text-sm text-muted-foreground">Block Time: </span>
              <span className="font-mono font-semibold text-primary">{formatTime(calculatedBlockTime)}</span>
            </div>
          )}
        </div>

        <div className="section-divider" />

        {/* Flight Time Override */}
        <div>
          <Label className="text-sm text-muted-foreground mb-2 flex items-center gap-1.5">
            <Timer className="h-3.5 w-3.5" />
            Flight Time (manual)
          </Label>
          <Input
            type="text"
            placeholder="e.g. 1h30"
            value={flightTime}
            onChange={(e) => setFlightTime(e.target.value)}
            className="font-mono"
          />
        </div>

        <div className="section-divider" />

        {/* Landings */}
        <div>
          <Label className="text-sm text-muted-foreground mb-2 flex items-center gap-1.5">
            <PlaneLanding className="h-3.5 w-3.5" />
            Landings
          </Label>
          <Input
            type="number"
            min="0"
            value={landings}
            onChange={(e) => setLandings(e.target.value ? parseInt(e.target.value) : '')}
            className="font-mono text-center w-24"
          />
        </div>

        <div className="section-divider" />

        {/* Fuel */}
        <div>
          <Label className="text-sm text-muted-foreground mb-2 flex items-center gap-1.5">
            <Fuel className="h-3.5 w-3.5" />
            Fuel
          </Label>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label className="text-xs text-muted-foreground">Initial (gal)</Label>
              <Input
                type="text"
                value={initialFuelGallons}
                disabled
                className="font-mono text-right bg-muted"
              />
            </div>
            <div>
              <Label className="text-xs text-muted-foreground">Remaining (gal)</Label>
              <Input
                type="number"
                min="0"
                max={initialFuelGallons}
                placeholder="0"
                value={fuelRemaining}
                onChange={(e) => setFuelRemaining(e.target.value ? parseFloat(e.target.value) : '')}
                className="font-mono text-right"
              />
            </div>
          </div>
          {fuelUsed !== null && fuelUsed > 0 && (
            <div className="mt-2 text-center">
              <span className="text-sm text-muted-foreground">Used: </span>
              <span className="font-mono font-semibold text-aviation-amber">{fuelUsed.toFixed(1)} gal</span>
              {hobbsTime && hobbsTime > 0 && (
                <span className="text-xs text-muted-foreground ml-2">
                  ({(fuelUsed / hobbsTime).toFixed(1)} gal/h)
                </span>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
